# -*- coding: utf-8 -*-
"""ProjectKP_UngkapKasus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yg9XZdAuYgyc6r1GLTV6evot7Z1mUC5Q
"""

import re
import string
import pandas as pd
import numpy as np
import seaborn as sns
import geopandas as gpd

import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

"""## 1. Membaca data"""

df1 = pd.read_excel("KasusClean.xlsx")

df1.info()
print(df1.head(5))

"""## 2. Data cleaning"""

print(df1.duplicated().sum())

"""Menghapus kolom yang tidak relevan atau tidak penting  
- No: tidak memiliki fungsi untuk pemodelan  
- Jumlah tersangka: karena data sudah dipisah menjadi 1 baris per individu bukan per kasus maka bisa dihapus
"""

df1 = df1.drop(columns=['No', 'Jumlah Tersangka'])

"""Standarisasi kolom besaran/jumlah bb dalam gram dan butir"""

df1['Besaran/Jumlah BB'] = df1['Besaran/Jumlah BB'].astype(str)
df1["Pekerjaan"] = df1["Pekerjaan"].str.strip()

df1['Besaran/Jumlah BB'] = df1['Besaran/Jumlah BB'].str.replace(
    r',\s+',
    ',',
    regex=True
)

# Ngatasin spasi setelah koma
df1['bb_satuan'] = df1['Besaran/Jumlah BB'].str.extract(
    r'(gram|butir)', flags=re.IGNORECASE
)

# Untuk satuan gram
df1['BB_gram'] = (
    df1['Besaran/Jumlah BB']
    .str.findall(r'([\d,]+)\s*gram')
    .apply(
        lambda x: sum(float(i.replace(',', '.')) for i in x) if len(x) > 0 else 0
    )
)

# Untuk satuan butir
df1['BB_butir'] = (
    df1['Besaran/Jumlah BB']
    .str.findall(r'([\d\.]+)\s*butir')
    .apply(
        lambda x: sum(float(i.replace('.', '')) for i in x) if len(x) > 0 else 0
    )
)

df1 = df1.drop(columns=['bb_satuan'])

print(df1)

"""## 3. Feature Engineering"""

agg_kecamatan = df1.groupby('Kecamatan').agg(
    jumlah_kasus=('Kecamatan', 'count'),
    total_gram=('BB_gram', 'sum'),
    total_butir=('BB_butir', 'sum')
).reset_index()

df1['Jenis BB'] = (
    df1['Jenis BB']
    .astype(str)
    .str.strip()
)

df1['Kecamatan'] = (
    df1['Kecamatan']
    .astype(str)
    .str.strip()
)

kasus_jenis = df1.groupby(['Kecamatan','Jenis BB']).size().reset_index(name='jumlah_kasus')

pivot_kasus = kasus_jenis.pivot_table(
    index='Kecamatan',
    columns='Jenis BB',
    values='jumlah_kasus',
    fill_value=0
)

print(pivot_kasus)

"""## 4. EDA"""

kasus_per_kecamatan = (
    df1.groupby('Kecamatan')
       .size()
       .sort_values(ascending=False)
)

print(kasus_per_kecamatan)

plt.figure()
kasus_per_kecamatan.plot(kind='bar')
plt.title('Jumlah Kasus per Kecamatan')
plt.xlabel('Kecamatan')
plt.ylabel('Jumlah Kasus')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

kasus_per_tahun = (
    df1.groupby('Tahun')
       .size()
       .sort_index()
)

plt.figure()
kasus_per_tahun.plot(kind='bar')
plt.title('Jumlah Kasus Penyalahgunaan Narkoba per Tahun')
plt.xlabel('Tahun')
plt.ylabel('Jumlah Kasus')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

kasus_pekerjaan = (
    df1.groupby('Pekerjaan')
       .size()
       .sort_index()
       .sort_values(ascending=False)
)

plt.figure()
kasus_pekerjaan.plot(kind='bar')
plt.title('Jumlah Kasus per Pekerjaan')
plt.xlabel('Pekerjaan')
plt.ylabel('Jumlah Kasus')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

kasus_tahun_pekerjaan = (
    df1.groupby(['Tahun', 'Pekerjaan'])
       .size()
       .unstack(fill_value=0)
)

kasus_tahun_pekerjaan.plot(
    kind='bar',
    stacked=True,
    colormap='tab20'
)

plt.title('Jumlah Kasus per Tahun di Tiap Pekerjaan')
plt.xlabel('Tahun')
plt.ylabel('Jumlah Kasus')
plt.xticks(rotation=0)
plt.legend(title='Pekerjaan', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

kasus_tahun_kecamatan = (
    df1.groupby(['Tahun', 'Kecamatan'])
       .size()
       .unstack(fill_value=0)
)

kasus_tahun_kecamatan.plot(
    kind='bar',
    stacked=True,
    colormap='tab20'
)

plt.title('Jumlah Kasus per Tahun di Tiap Kecamatan')
plt.xlabel('Tahun')
plt.ylabel('Jumlah Kasus')
plt.xticks(rotation=0)
plt.legend(title='Kecamatan', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

#
bb_per_kecamatan_gram = (
    df1.groupby('Kecamatan')[['BB_gram']]
       .sum()
       .sort_values(by=['BB_gram'], ascending=False)
)

bb_per_kecamatan_butir = (
    df1.groupby('Kecamatan')[['BB_butir']]
       .sum()
       .sort_values(by=['BB_butir'], ascending=False)
)

print(bb_per_kecamatan_gram)
print("\n")
print(bb_per_kecamatan_butir)

bb_per_kecamatan_gram.sort_values('BB_gram', ascending=False).head(10).plot(
    kind='bar',
    y='BB_gram',
    title='Top 10 Kecamatan berdasarkan Total BB (Gram)'
)

bb_per_kecamatan_butir.sort_values('BB_butir', ascending=False).head(10).plot(
    kind='bar',
    y='BB_butir',
    title='Top 10 Kecamatan berdasarkan Total BB (Butir)'
)

fitur_kecamatan = (
    df1.groupby('Kecamatan')
       .agg(
           jumlah_kasus=('Kecamatan', 'size'),
           total_gram=('BB_gram', 'sum'),
           total_butir=('BB_butir', 'sum')
       )
       .reset_index()
)

print(fitur_kecamatan)

"""## 5. Standarisasi

Standard Scaler
"""

X = fitur_kecamatan[['jumlah_kasus', 'total_gram', 'total_butir']]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled)

X_scaled_df = pd.DataFrame(
    X_scaled,
    columns=X.columns,
    index=fitur_kecamatan['Kecamatan']
)

print(X_scaled_df.head())

"""Standard Scaler lebih cocok digunakan untuk kasus ini karena tujuannya adalah untuk memetakan wilayah rawan dengan clustering kecamatan dan menggunakan analisis yang berbasis jarak (Euclidean Distance)

MinMax Scaler
"""

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

X_scaled_df = pd.DataFrame(
    X_scaled,
    index=X.index,
    columns=X.columns
)

print(X_scaled_df)

"""## 6. Elbow Method"""

wcss = []
K_range = range(1, 11)

for k in K_range:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    kmeans.fit(X_scaled_df)
    wcss.append(kmeans.inertia_)

plt.figure()
plt.plot(K_range, wcss, marker='o')
plt.title('Elbow Method untuk Menentukan Jumlah Cluster')
plt.xlabel('Jumlah Cluster (K)')
plt.ylabel('WCSS / Inertia')
plt.xticks(K_range)
plt.tight_layout()
plt.show()

"""Tujuan menggunakan elbow method adalah untuk menentukan cluster yang paling optimal dengan melihat penurunan WCCS/Inertia dari titik "siku" dan mulai melandai"""

for k in range(2, 7):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_scaled_df)
    score = silhouette_score(X_scaled_df, labels)
    print(f'K={k}, Silhouette Score={score:.3f}')

"""Penggunaan silhouette score agar semakin meyakinkan dengan menampilkan hasil dalam bentuk angka, semakin mendekati 1 semakin bagus clusternya (yaitu cluster 3)

## 7. Pemodelan K-Means
"""

# Tentukan jumlah cluster
k = 2

kmeans = KMeans(
    n_clusters=k,
    random_state=42,
    n_init=10
)

# Fit model dan prediksi cluster
fitur_kecamatan['cluster'] = kmeans.fit_predict(X_scaled_df)
fitur_kecamatan['cluster'] = fitur_kecamatan['cluster'].map({0: 1, 1: 0})

print(fitur_kecamatan)

"""Model K-Means digunakan untuk mengelompokkan kecamatan berdasarkan kemiripan karakteristik penyalahgunaan narkoba, yang meliputi jumlah kasus, total barang bukti dalam satuan gram, dan total barang bukti dalam satuan butir.

Sebelum pemodelan, data dinormalisasi menggunakan StandardScaler untuk menghindari dominasi fitur dengan skala besar. Jumlah cluster ditentukan menggunakan metode Elbow.

Hasil clustering menunjukkan adanya pengelompokan wilayah ke dalam kategori tingkat kerawanan yang berbeda, yaitu wilayah relatif aman, wilayah rawan sedang, dan wilayah rawan tinggi.

## 8. Interpretasi Cluster
"""

cluster_summary = (
    fitur_kecamatan
    .groupby('cluster')
    .agg(
        jumlah_kasus_mean=('jumlah_kasus', 'mean'),
        total_gram_mean=('total_gram', 'mean'),
        total_butir_mean=('total_butir', 'mean'),
        jumlah_kecamatan=('cluster', 'count')
    )
)

print(cluster_summary)

"""- Cluster 0 (Kerawanan Rendah)
Kecamatan dengan jumlah kasus dan barang bukti relatif rendah. Wilayah ini cenderung stabil dan dapat dijadikan zona pemeliharaan pencegahan.

- Cluster 1 (Kerawanan Sedang)
Kecamatan dengan tingkat kasus dan barang bukti sedang. Wilayah ini perlu pengawasan dan intervensi preventif tambahan.

- Cluster 2 (Kerawanan Tinggi)
Kecamatan dengan jumlah kasus dan barang bukti paling tinggi. Wilayah ini menjadi prioritas utama dalam penegakan hukum dan program rehabilitasi.

## 9. Validasi (Unsupervised)
"""

sil_score = silhouette_score(X_scaled_df, fitur_kecamatan['cluster'])
print(sil_score)

fitur_kecamatan['cluster'].value_counts().sort_index().plot(kind='bar')
plt.title('Jumlah Kecamatan pada Tiap Cluster')
plt.xlabel('Cluster')
plt.ylabel('Jumlah Kecamatan')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""## 10. Pemetaan Wilayah"""

df_cluster = fitur_kecamatan.copy()

gdf_map = gpd.read_file("34.04_kecamatan.geojson")

print(gdf_map.columns)
print(df_cluster.columns)

gdf_map['kecamatan'] = gdf_map['nm_kecamatan'].str.strip().str.lower()
df_cluster['Kecamatan'] = df_cluster['Kecamatan'].str.strip().str.lower()

gdf_merge = gdf_map.merge(
    df_cluster,
    left_on='kecamatan',
    right_on='Kecamatan',
    how='left'
)

gdf_map.plot(
    edgecolor='black',
    facecolor='none'
)

plt.title('Peta Kecamatan (GeoJSON Mentah)')
plt.axis('off')
plt.show()

gdf_merge.plot(
    column='cluster',
    cmap='RdYlGn_r',
    legend=True,
    edgecolor='black',
    missing_kwds={
        "color": "white",
        "edgecolor": "black",
        "label": "Tidak ada data"
    }
)

plt.title('Peta Tingkat Kerawanan Penyalahgunaan Narkoba per Kecamatan')
plt.axis('off')
plt.show()

def generate_labels(n):
    labels = []
    alphabet = string.ascii_uppercase
    i = 0
    while len(labels) < n:
        label = ""
        x = i
        while True:
            label = alphabet[x % 26] + label
            x = x // 26 - 1
            if x < 0:
                break
        labels.append(label)
        i += 1
    return labels

labels = generate_labels(len(gdf_merge))
gdf_merge['label'] = labels

gdf_merge['centroid'] = gdf_merge.geometry.centroid

fig, ax = plt.subplots(1, 1, figsize=(10, 10))

gdf_merge.plot(
    column='cluster',
    cmap='RdYlGn_r',
    legend=True,
    edgecolor='black',
    missing_kwds={
        "color": "white",
        "edgecolor": "black",
        "label": "Tidak ada data"
    },
    ax=ax
)

for idx, row in gdf_merge.iterrows():
    if row['centroid'] is not None:
        ax.text(
            row['centroid'].x,
            row['centroid'].y,
            row['label'],
            fontsize=9,
            ha='center',
            va='center',
            fontweight='bold'
        )

ax.set_title('Peta Tingkat Kerawanan Penyalahgunaan Narkoba per Kecamatan')
ax.axis('off')
plt.show()

legend_table = gdf_merge[['label', 'nm_kecamatan']].sort_values('label')
legend_table.rename(
    columns={
        'label': 'Kode',
        'nm_kecamatan': 'Nama Kecamatan'
    },
    inplace=True
)

legend_table